/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.administrador;

import controlador.NegocioDao;
import java.awt.FlowLayout;
import javax.swing.JMenu;
import modelo.Negocio;
import modelo.Usuario;

/**
 *
 * @author jmcbg
 */
public class VentanaAdmin extends javax.swing.JFrame {

    private Usuario usuario;

   

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaAdmin(Usuario user) {
        usuario = user;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesMenu = new javax.swing.ButtonGroup();
        contenido = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        botonInfo = new javax.swing.JMenu();
        botonProductos = new javax.swing.JMenu();
        botonOpciones = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Mercader");
        setResizable(false);

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 0));

        botonInfo.setBackground(new java.awt.Color(255, 102, 0));
        botonInfo.setForeground(new java.awt.Color(255, 255, 255));
        botonInfo.setText("INICIO");
        botonesMenu.add(botonInfo);
        botonInfo.setDoubleBuffered(true);
        botonInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deselección(evt);
            }
        });
        jMenuBar1.add(botonInfo);

        botonProductos.setBackground(new java.awt.Color(255, 102, 0));
        botonProductos.setForeground(new java.awt.Color(255, 255, 255));
        botonProductos.setText("USUARIOS");
        botonesMenu.add(botonProductos);
        botonProductos.setDoubleBuffered(true);
        botonProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deselección(evt);
            }
        });
        jMenuBar1.add(botonProductos);

        botonOpciones.setText("NEGOCIOS");
        botonesMenu.add(botonOpciones);
        botonOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonOpciones.setDoubleBuffered(true);
        botonOpciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deselección(evt);
            }
        });
        jMenuBar1.add(botonOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deselección(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deselección
       JMenu jm = (JMenu) evt.getComponent();
       jm.setSelected(false);
    }//GEN-LAST:event_deselección

 
   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botonInfo;
    private javax.swing.JMenu botonOpciones;
    private javax.swing.JMenu botonProductos;
    private javax.swing.ButtonGroup botonesMenu;
    private javax.swing.JPanel contenido;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
