/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.paneles;

import controlador.conexion;
import javax.swing.JOptionPane;
import modelo.direccion;
import modelo.usuario;

/**
 *
 * @author JM
 */
public class direccionUsuario extends javax.swing.JPanel {

    private usuario usuarioActual;
    private conexion conex;

    /**
     * Creates new form informacionUsuario
     */
    public direccionUsuario(usuario user, conexion conex) {
        initComponents();
        this.conex = conex;
        this.usuarioActual = user;
        mostrarContenido();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nombre3 = new javax.swing.JLabel();
        nombre5 = new javax.swing.JLabel();
        provincia = new javax.swing.JTextField();
        numerotxt = new javax.swing.JLabel();
        nombre12 = new javax.swing.JLabel();
        nombre13 = new javax.swing.JLabel();
        nombre14 = new javax.swing.JLabel();
        nombre8 = new javax.swing.JLabel();
        bloque = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        piso = new javax.swing.JTextField();
        puerta = new javax.swing.JTextField();
        coordenadas = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        calle = new javax.swing.JTextField();

        setBackground(new java.awt.Color(239, 246, 253));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(626, 188));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(626, 188));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(239, 246, 253));
        title.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        title.setText("DIRECCIÓN");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 420, -1));

        nombre1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombre1.setText("Puerta:");
        add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 80, -1));

        jButton1.setText("GUARDAR CAMBIOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 160, -1));

        nombre3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombre3.setText("Coordenadas:");
        add(nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, -1));

        nombre5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombre5.setText("Bloque:");
        add(nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 70, -1));

        provincia.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaActionPerformed(evt);
            }
        });
        add(provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 200, 24));

        numerotxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        numerotxt.setText("Número:");
        add(numerotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 97, -1));

        nombre12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombre12.setText("Calle:");
        add(nombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        nombre13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombre13.setText("Ciudad:");
        add(nombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, -1));

        nombre14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombre14.setText("Provincia:");
        add(nombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 80, -1));

        nombre8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombre8.setText("Piso:");
        add(nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 70, -1));

        bloque.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        bloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloqueActionPerformed(evt);
            }
        });
        add(bloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 70, 24));

        numero.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 30, 24));

        piso.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        piso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pisoActionPerformed(evt);
            }
        });
        add(piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 70, 24));

        puerta.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        puerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertaActionPerformed(evt);
            }
        });
        add(puerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 70, 24));

        coordenadas.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        coordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordenadasActionPerformed(evt);
            }
        });
        add(coordenadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 460, 24));

        ciudad.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });
        add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, 24));

        calle.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calleActionPerformed(evt);
            }
        });
        add(calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 460, 24));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        edicionDireccionUsuario();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinciaActionPerformed

    private void bloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloqueActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void pisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pisoActionPerformed

    private void puertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puertaActionPerformed

    private void coordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordenadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coordenadasActionPerformed

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadActionPerformed

    private void calleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloque;
    private javax.swing.JTextField calle;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField coordenadas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre12;
    private javax.swing.JLabel nombre13;
    private javax.swing.JLabel nombre14;
    private javax.swing.JLabel nombre3;
    private javax.swing.JLabel nombre5;
    private javax.swing.JLabel nombre8;
    private javax.swing.JTextField numero;
    private javax.swing.JLabel numerotxt;
    private javax.swing.JTextField piso;
    private javax.swing.JTextField provincia;
    private javax.swing.JTextField puerta;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private void mostrarContenido() {
        direccion direccionTMP = usuarioActual.getDireccion();
        calle.setText(direccionTMP.getCalle());
        numero.setText(direccionTMP.getNumero());
        bloque.setText(direccionTMP.getBloque());
        piso.setText(direccionTMP.getPiso());
        puerta.setText(direccionTMP.getPuerta());
        ciudad.setText(direccionTMP.getCiudad());
        provincia.setText(direccionTMP.getProvincia());
        coordenadas.setText(direccionTMP.getCoordenadas());

    }

    private void actualizar() {
        usuarioActual = controlador.usuarioDAO.obtenerUsuarioPricipal(conex, usuarioActual);
    }

    private void edicionDireccionUsuario() {
        direccion direccionTMP = new direccion();
        direccionTMP.setBloque(bloque.getText());
        direccionTMP.setCalle(calle.getText());
        direccionTMP.setCiudad(ciudad.getText());
        direccionTMP.setCoordenadas(coordenadas.getText());
        direccionTMP.setNumero(numero.getText());
        direccionTMP.setPiso(piso.getText());
        direccionTMP.setProvincia(provincia.getText());
        direccionTMP.setPuerta(puerta.getText());
        usuarioActual.setDireccion(direccionTMP);
        if (controlador.usuarioDAO.editarUsuario(conex, usuarioActual)) {
            JOptionPane.showMessageDialog(null, "Información actualizada Correctamente");
        }
        actualizar();
        mostrarContenido();
    }
}
