/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.paneles;

import controlador.conexion;
import controlador.contratosDAO;
import controlador.tarifaDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.contrato;
import modelo.tarifa;
import modelo.usuario;

/**
 *
 * @author JM
 */
public class tarifasUsuarios extends javax.swing.JPanel {

    private usuario usuarioActual;
    private conexion conex;

    /**
     * Creates new form informacionUsuario
     *
     * @param user
     * @param conex
     */
    public tarifasUsuarios(usuario user, conexion conex) {
        initComponents();
        this.conex = conex;
        this.usuarioActual = user;
        mostrarContenido();

    }

    private void mostrarContenido() {
        recargarTablaEmpleados(tarifaDAO.obtenerTarifas(conex));
    }

    public void recargarTablaEmpleados(ArrayList<tarifa> listaTarifas) {
        tablaTarifas.setModel(
                new DefaultTableModel(null, new String[]{"Número Tarifa", "Velocidad", "Permanencia","PRECIO"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        //tablaEmpleados.getColumnModel().getColumn(0).setMaxWidth(60);
        //tablaEmpleados.getColumnModel().getColumn(2).setMinWidth(100);
        tablaTarifas.setAutoCreateRowSorter(true);
        for (tarifa Tarifa : listaTarifas) {
            DefaultTableModel model = (DefaultTableModel) tablaTarifas.getModel();
            model.addRow(tarifa2row(Tarifa));
        }
    }

    public Object[] tarifa2row(tarifa tarifa) {
        return new Object[]{tarifa.getId(), tarifa.getVelocidad(), tarifa.isPermanencia(),tarifa.getPrecio()};
    }

    private void actualizarUsuario() {
        usuarioActual = controlador.usuarioDAO.obtenerUsuarioPricipal(conex, usuarioActual);
    }
    private void altaTarifa() {
        if (tablaTarifas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "TIENES QUE SELECCIONAR UNA TARIFA PARA CONTRATARLA!", "Starconex: ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            int decision = JOptionPane.showOptionDialog(
                    this,
                    "SEGURO QUE DESEA CONTRATAR LA TARIFA SELECCIONADA?",
                    "Starconex: Contratación",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null, // null para icono por defecto.
                    new Object[]{"NO CONTRATAR", "SÍ CONTRATAR"}, // null para YES, NO y CANCEL
                    "NO CONTRATAR");
            if (decision == 1) {
                actualizarUsuario();
               tarifaDAO.contratarTarifa(conex, usuarioActual, new tarifa((int) tablaTarifas.getModel().getValueAt(tablaTarifas.getSelectedRow(), 0)));
                mostrarContenido();
            }
        }

    }

    private void edicionUsuario() {
//        usuario usuarioEditado = usuarioActual;
//        usuarioEditado.setNombre(nombre.getText());
//        usuarioEditado.setApellidos(apellidos.getText());
//        usuarioEditado.setTelefono(telefono.getText());
//        if (controlador.usuarioDAO.editarUsuario(conex, usuarioActual)) {
//            actualizar();
//            mostrarContenido();
//            JOptionPane.showMessageDialog(null, "Información actualizada Correctamente");
//        }
//        actualizar();
//        mostrarContenido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTarifas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(626, 171));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(626, 171));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(239, 246, 253));
        title.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        title.setText("CONTRATAR TARIFA:");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 300, 20));

        jButton1.setText("MÁS INFORMACIÓN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 160, -1));

        tablaTarifas.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Número", "Nombre", "Localización"
            }
        ));
        tablaTarifas.setShowGrid(true);
        jScrollPane1.setViewportView(tablaTarifas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 580, 110));

        jButton2.setText("CONTRATAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        altaTarifa();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        edicionUsuario();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTarifas;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    
}
